version: 2
updates:
  
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  
  # Maintain dependencies for NuGet for all csproj projects
  - package-ecosystem: "nuget"
    directory: "/src/**/*.csproj"
    schedule:
      interval: "daily"
