name: Publish to nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: src/Likvido.Worker.AzureStorageQueue.csproj
          PACKAGE_NAME: Likvido.Worker.AzureStorageQueue
          VERSION_REGEX: <ReleaseVersion>(.*)<\/ReleaseVersion>
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
