name: Publish to nuget

on:
  push:
    branches:
      - master
    paths:
      - version.props
      - .github/workflows/nuget.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Publish NuGet
        uses: likvido/github-actions/simple-nuget@nuget-v1.1
        with:
          project: src/Likvido.Worker.AzureStorageQueue.csproj
          nuget-key: ${{ secrets.NUGET_API_KEY }}
